[package]
name = "big-brain"
version = "0.15.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2021"
description = "Rusty Utility AI library"
license = "Apache-2.0"
readme = "README.md"
keywords = ["utility-ai", "bevy", "ai", "ecs"]
categories = ["game-development"]
repository = "https://github.com/zkat/big-brain"
homepage = "https://github.com/zkat/big-brain"

[workspace]

[dependencies]
bevy = { version = "0.9.0", default-features = false }
big-brain-derive = { version = "0.2.1", path = "./derive" }

[dev-dependencies]
bevy = { version = "0.9.0", default-features = true }

[features]
trace = []
